### ISSUE TITLE
라이브러리 페이지 자동화 개선

### ISSUE THREAD

**Issue by junnaa** [xpressengine/XEIcon#1]
### URL : 
http://xpressengine.github.io/XEIcon/

### 요구사항 
- https://icomoon.io/app/#/projects 에서 버전별로 수정 진행한 사항이 
같은 class를 가진 아이콘은 자동 대체/연동되도록.

- 분류항목이 라이브러리에 포함되도록 개선. 

- html tag / Unicode HTML Entity 를 Copy할 수 있도록 개발. 
  - http://fontawesome.bootstrapcheatsheets.com/#home 참조.

**Comment by bnu** [comment]
완료.

* `orginallibrary` 브랜치의 README.md 참고
* `gh-pages` 브랜치는 별도로 수정을 하지 않도록 한다
* 디자인 등 구성 변경이 필요한 경우 `orginallibrary` 브랜치의 `src` 디렉토리의 파일을 편집할 것
