### ISSUE TITLE
glyph Icons 추가요청

### ISSUE THREAD

**Issue by samswnlee** [xpressengine/XEIcon#14]
현재 XEIcon은 예쁘장 하지만 단조로워서
활용도가 조금 떨어지는 경향이 있습니다.

폰트어썸처럼 테두리형 아이콘과 색칠된 아이콘 두가지 형태로 제공하면
좀더 넓은 활용도를 지닐수 있을것 같습니다,

**Comment by junnaa** [comment]
Boxed Icon 요청사항은 어떻게 진행할지 검토중에 있습니다.
v2에 배포할 계획입니다.
의견 감사합니다. ^^
