### ISSUE TITLE
아이콘 테두리 및 들여쓰기

### ISSUE THREAD

**Issue by yeoreume** [xpressengine/XEIcon#15]
http://i.imgur.com/FioNmKE.jpg

첫번째. XEIcon 예제소스 적용
두번째. FontAwesome 예제소스 적용
세번째. FontAwesome 소스에 XEicon만 삽입
+) 비슷하게는 나오는데 테두리와 글 사이에 여백이 사라짐.

NginX 1.7.9
PHP 5.6.7
MariaDB 10
XE 1.8

스케치북레이아웃, 스킨, 새로 추가된 레이아웃, 스킨
어디에 적용해도 똑같이 뭉개지네요.

**Comment by junnaa** [comment]
@yeoreume 
f0a4ca34a4afbd7c7b444e4bf5665c70efcaabe2
- 문제 : example 페이지 예시 및 gh-page에 적용된 소스 모두 잘못 기입
- 해결 : example 페이지 소스 및 예제 텍스트 수정 완료
