### ISSUE TITLE
:after 에 content 에서 하는데  혹시 xeicon 에서도 가능한가요..??

### ISSUE THREAD

**Issue by ppleo** [xpressengine/XEIcon#16]
.locNav li a:after{content: "\f105";font-family: Fontawesome;font-size: 14px;float: right; padding-right: 20px;}

폰트 어썸에서는위처럼 content 에서 하는데  혹시 xeicon 에서도 가능한가요..??

**Comment by gunil** [comment]
대부분 아이콘폰트의 경우 가상선택자를 사용하기에 가능합니다.
하지만 현재 라이브러리 페이지에서는 바로 확인이 어렵구요.
css 파일을 찾아서 적용해야 하는 번거로움이 있습니다. (이부분은 향후에 검토후 적용하도록 하겠습니다)
https://github.com/xpressengine/XEIcon/blob/master/xeicon.css

가령 xi-home 아이콘을 노출시키고자 한다면, 아래처럼 적용하시면 됩니다.
.selector:after{font-family:'xeicon';content:'\e606'}

**Comment by junnaa** [comment]
#26 유니코드 라이브러리 노출
