### ISSUE TITLE
홈페이지 gh-pages에서 Library 페이지

### ISSUE THREAD

**Issue by DingGGu** [xpressengine/XEIcon#17]
http://xpressengine.github.io/XEIcon/library_common.html
Library 페이지에서 검색 후 없다면 Github 버튼이 나오는데 누르면 Hash처리만 되어있네요.

까먹고 링크 설정 안하신 듯 해요.

**Comment by junnaa** [comment]
@DingGGu 
재반영 완료하였습니다. 
감사합니다. ^^

**Comment by bnu** [comment]
:+1:
