### ISSUE TITLE
건강 카테고리 아이콘도 넣어주시면 안될까요?

### ISSUE THREAD

**Issue by misol** [xpressengine/XEIcon#18]
첫 배포에서는 xe-pill (알약)이 있었는데, 1.0.4에선 사라졌어요.
건강 카테고리(테마?) 도 하나 추가해주시면 안될까요?!?!

**Comment by bnu** [comment]
:+1:

**Comment by junnaa** [comment]
의류, 건강 등의 카테고리는 추가건은 Thin 버전 배포 후 v2.x 마일스톤에 추가할 예정입니다.
의견 감사합니다.

**Comment by misol** [comment]
슝슝 화이팅!!
