### ISSUE TITLE
LESS, SASS 적용 / 기능탑재

### ISSUE THREAD

**Issue by junnaa** [xpressengine/XEIcon#2]
## LESS, SASS 기능 추가 
- Lager Icons `minor`
- Fixed Width icons `minor`
- Bordered & Pulled Icons `minor`
- Spinning Icons `major`
- Rotated & Flipped `major`
- Stacked Icons `critical`
- Custom CSS `contributors`

## Requirement / Request
- from 재아<jaea@hanmail.net>
폰트어썸에서 사용하는 아이콘 돌리기? 아이콘 겹치기? 아이콘 키우기? 아이콘 회전 시키기 등이 가능한데... xe도 이부분에 대하여 추가적으로 개발을 할껀지요?
- Developers@xpressengine.com
아이콘을 회전하는 것은 업데이트를 계획하고 있습니다.
다만, 아이콘을 쌓아 합치거나 크기 변경을 위한 스타일은 검토 단계에 있으며,
결과에 따라 구현되지 않을 수 있습니다.

## Example urls
- SASS/LESS : http://fontawesome.io/examples/
- CSS-Tricks : http://css-tricks.com/star-ratings/

**Comment by junnaa** [comment]
## 상세일정

- 리뷰 : 01.09
- 배포 : 01.12
- 작업 : @LeeYoonGu @findstar / @zoon0001 @gunil

## 항목
추가 항목 및 기본항목에서 필요한 것만 기본배포.
기타 한국 웹문화에 적절한 LESS,SASS 적용안 검토/아이디어 회의

### 기본항목
### 추가항목

**Comment by junnaa** [comment]
## 버전관리 및 운영
- SASS, LESS 적용파일은 1.0.3 기준으로 배포함.

**Comment by junnaa** [comment]
빌드스크립트 개선 @bnu

**Comment by bnu** [comment]
test

**Comment by bnu** [comment]
test
