### ISSUE TITLE
i tag 사용 고려

### ISSUE THREAD

**Issue by ajkj** [xpressengine/XEIcon#21]
현재 xeicon에 기본으로 제공되는 xeicon.css에서 i tag 속성 자체를 변경 하고 있습니다.

이 경우 i tag 자체를 사용하고 싶어도(italic 체) 별도로 다시 기본값으로 초기화 해 주어야 합니다.

충돌이 없도록, .xi 등의 class를 적용한것에 한해 초기화가 진행되면 좋을것 같습니다.

다른 icon font 들도 유사하게 진행하고 있는것으로 알고 있습니다.

```
<i class="xi xi-comment"></i> 
```

https://github.com/xpressengine/XEIcon/blob/master/xeicon.css#L20

**Comment by gunil** [comment]
좋은 의견 주셔서 감사합니다.
검토 후 반영토록 하겠습니다.

**Comment by bnu** [comment]
2.3.3 버전에서 처리했으며, 'xi' 클래스를 추가하지 않고 처리하였습니다.
