### ISSUE TITLE
브라우져 글꼴 고정에 따른 아이콘 깨짐 문제

### ISSUE THREAD

**Issue by hunnick** [xpressengine/XEIcon#22]
구글 크롬의 최신 버전에서, '확장 프로그램'으로 글꼴을 강제로 지정하면 모든 아이콘이 ㅁ로 표시됩니다.

제가 고정한 글꼴은 "맑은 고딕"입니다.

**Comment by gunil** [comment]
xeicon도 폰트의 일종이기에 글꼴을 강제로 지정하시면 안될 것 같습니다.
현재 버전 기준으로 <i> 태그에 font-family: xeicon 까지 맑은고딕으로 강제되어 제대로 랜더링 되지 않는 현상으로 판단됩니다.

**Comment by hunnick** [comment]
@gunil 
제가 내용을 기재한 까닭은 크롬의 '확장 프로그램'으로 글꼴을 강제 지정하여 사용하는 사용자가 많기 때문입니다.
XEicon도 폰트의 일종이니 아이콘이 포함되지 않는 글꼴에서는 ㅁ로 표시되겠지요. 잘 알고 있습니다.
이에 대한 해결방법이 현재는 없는것인지, 앞으로도 없을것인지, 문제를 인식하고 해결을 하는 방향을 고려해볼 것인지에 대해
사용자로서 문제점을 알려드린겁니다.
감사합니다.

**Comment by bnu** [comment]
@hunnick 폰트 지정을 대체해버리기 때문에 XEIcon에서 해결할 수 있는 것이 아닙니다.
폰트를 대체하기위해 보통 `* { font-family: "맑은 고딕 !important"; };` 처럼 지정하는데, 이는 XEIcon 외에도 모든 아이콘 폰트도 마찬가지로 영향을 받습니다.

다음 링크를 참고하시면 도움이 되실겁니다.
링크의 글은 Mac OS 환경에 대해 설명하고 있지만 증상과 원인, 그리고 해결 방법은 OS 차이에 영향이 없습니다.
- [맥용 사파리가 웹 페이지의 아이콘을 제대로 표시하지 못한다면? CSS 설정을 확인하세요](http://macnews.tistory.com/1871)
- [국내 웹 환경을 위한 보다 스마트한 웹브라우저용 스타일시트(CSS) - 이제 필요한 서체만 선별적으로 바꿔쓰세요.](http://macnews.tistory.com/162)
