### ISSUE TITLE
설치-가장 쉬운 방법(Easiest) : CDN by jsDelivr HTML 코드 오류

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/XEIcon#23]
`사이트 <head> 태그 안에 아래의 코드를 붙입니다.` 하단 코드 중
```html
<link rel=“stylesheet” href=“//cdn.jsdelivr.net/xeicon/1.0.4/xeicon.min.css”>
```
위와 같이 `"`가 `“`와 `”`로 잘못 사용되었습니다.
HTML에서는 서로 엄연히 다른 문자로, 위 코드를 그대로 붙여 넣으면 오동작하게 됩니다.

**Comment by junnaa** [comment]
7abc8f382709cc2d99b04043f047e028c17fadd7
report 감사합니다. ^^
