### ISSUE TITLE
전 포인트 관련 아이콘이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by ppleo** [xpressengine/XEIcon#24]
돈이나 포인트 관련 아이콘이 없습니다.

아래는 아이콘 몬스터에서 검색한 것 입니다. ^^

http://iconmonstr.com/?s=money

**Comment by junnaa** [comment]
돈과 포인트 관련 아이콘은 기 제작되었으나 검토 후 반영하고자 차후 버전에 제공할 예정입니다.
의견 감사합니다. ^^
