### ISSUE TITLE
Examples-크기 조절 아이콘 예제 오류

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/XEIcon#25]
![image](https://cloud.githubusercontent.com/assets/5893514/8698125/df818f18-2b35-11e5-89df-42042b05c897.png)
예제 코드에는 1x,2x,3x,4x,5x라고 되어 있으나 옆 아이콘 옆 설명은 x1,x2,x3,x4,x5라고 잘못 설명하고 있습니다.

**Comment by gunil** [comment]
리포팅 감사드립니다.
확인 후 수정하였습니다.
