### ISSUE TITLE
500px 아이콘 추가 요청

### ISSUE THREAD

**Issue by kjkwt** [xpressengine/XEIcon#28]
개인적인 요청입니다만 차기 버전에서 
사진 공유 사이트인 500px의 아이콘도 추가되어 있으면 좋겠습니다.

Press의 Brand assets에서 현재의 로고를 확인할 수 있습니다.
https://about.500px.com/press/

font-awesome의 경우 아래와 같이 포함되어 있었습니다.
http://fortawesome.github.io/Font-Awesome/icon/500px/

**Comment by junnaa** [comment]
의견 감사합니다.
차기 버전에서 브랜드 아이콘에 추가하도록 하겠습니다.
