### ISSUE TITLE
단색으로된 아이콘

### ISSUE THREAD

**Issue by perzona420** [xpressengine/XEIcon#29]
XE아이콘 모두 뻥(?) 뚫려 있어서(선으로 구성됨) 선만 색을 줄 수 있어 아쉬워요.
배경이라고 하나?으로도 만들어 주셨으면 하네요 ㅎㅎ

**Comment by junnaa** [comment]
배포된 ver2.3.3 아이콘은 Filled 형태와 Outlined가 같이 제공됩니다. 모든 아이콘에 적용되어 있지 않고 반전이 가능한 아이콘에 한해서 제공하고 있습니다.
Outlined 아이콘은 `xi-name-o` 와 같이 클래스명이 붙어있으며, 필요한 경우(hover, active 등)에서 클래스명을 치환해주시면 됩니다.
