### ISSUE TITLE
모바일에서 아이콘이 보이지않는 문제

### ISSUE THREAD

**Issue by joyfuI** [xpressengine/XEIcon#34]
안드로이드 폰을 사용 중입니다. pc에서는 문제가 없는데 모바일에서 아이콘이 표시되지 않네요.
공식 홈페이지에서도 아무런 아이콘이 표시되지 않습니다.

**Comment by junnaa** [comment]
안녕하세요. 코멘트가 엄청 엄청 늦었습니다 ㅎ;
xe1의 공식홈에서는 xeicon 이전 버전을 font-awsome등과 혼합 사용중이며,
뜨지 않는 이유는 버전이 안맞게 퍼블리싱 되어 있어서 그런 것으로 보입니다.
xe3의 공홈에서는 ver2 라이브러리를 사용하여 잘 노출되고 있는 것으로 보입니다.

아이콘을 실제 사용하면서 문제가 되는 부분은 별도 이슈로 올려주시면 감사하겠습니다.
