### ISSUE TITLE
최신버전은 별도로 업데이트 진행해야 하나요?

### ISSUE THREAD

**Issue by samswnlee** [xpressengine/XEIcon#36]
xe내부에 포함된 버전이 1.0.4인데
2.2.0 은 별도로 사용해야하나요?
xe에 포함되게 할수는 없을까요?

**Comment by ghost** [comment]
최신 버전으로 업데이트를 진행하려 했으나 변경 사항이 많은 이유로 XE 1.9 버전에서 적용할 예정입니다.
(XE3에는 최신 버전이 적용되어 있습니다)

XE1에서 XEIcon 최신 버전을 사용하고자 하시는 경우 https://xpressengine.github.io/XEIcon/started.html 이 페이지를 참고하여 CDN을 이용한 적용을 하시거나 `common/xeicon/` 하위의 파일을 교체하셔야 합니다.
