### ISSUE TITLE
font-awesome 이랑 함께 사용할 때, 충돌합니다.

### ISSUE THREAD

**Issue by wan2land** [xpressengine/XEIcon#39]
![2017-08-14 12 21 30](https://user-images.githubusercontent.com/4086535/29250930-934870a0-8086-11e7-897d-5819a0138d36.png)

xeicon 에서 `<i>` 라는 태그에서 font-family를 !important로 선언해버려서
font-awesome 을 불러올 수 없습니다.

**Comment by wan2land** [comment]
fontawesome은 `<i class="fa fa-blabla">`와 같이 fa라는 클래스를 반드시 하나 추가해서 사용하는데,
xeicon의 경우 `<i class="xi-blabla">`와 같이 별도 클래스를 추가하지 않는 방식으로 사용해서
`<i>`태그에 기본 스타일을 정의해버린 것 같습니다.

`[class^="xi-"]` 와 같은 형식으로 대체하면 괜찮지 않을까 생각해봅니다.

**Comment by wan2land** [comment]
#21 에 이미 보고된 이슈군요.

**Comment by wan2land** [comment]
왠지 #35 도 같은 이슈인 것 같습니다.

**Comment by bnu** [comment]
2.3.3 버전에서 해결했습니다.
