### ISSUE TITLE
xe에 최신버전 아이콘 지원 안 하나요? ㅠㅠ

### ISSUE THREAD

**Issue by perzona420** [xpressengine/XEIcon#42]
안 나오네요. 몇몇 아이콘도..

**Comment by ghost** [comment]
@perzona420 XE1에는 1.0.4 버전이 포함되어 있습니다.
최신 버전으로 업데이트를 진행하려 했으나 변경 사항이 많은 이유로 XE 1.9 버전에서 적용할 예정입니다.
(XE3에는 최신 버전이 적용되어 있습니다)

XE1에서 XEIcon 최신 버전을 사용하고자 하시는 경우 https://xpressengine.github.io/XEIcon/started.html 이 페이지를 참고하여 CDN을 이용한 적용을 하시거나 `common/xeicon` 파일을 교체하셔야 합니다.

**Comment by perzona420** [comment]
@bnu 네, 감사합니다!
