### ISSUE TITLE
CONTRIBUTION Guide

### ISSUE THREAD

**Issue by junnaa** [xpressengine/XEIcon#5]
영문 : https://github.com/xpressengine/XEIcon/blob/master/CONTRIBUTING.md
한글 : https://github.com/xpressengine/XEIcon/blob/master/CONTRIBUTING_kor.md

@gunil @LeeYoonGu @niizguy 최종 확인 부탁드립니다.

**Comment by LeeYoonGu** [comment]
이상없어요 ^^
