### ISSUE TITLE
아이콘이 나타나지 않습니다.

### ISSUE THREAD

**Issue by Useol** [xpressengine/XEIcon#53]
안녕하세요. 
아이콘이 현재 지금 다 나타나지 않는 것 같습니다.
공식 사이트에서도 안보이네요.
확인 부탁드립니다.

**Comment by bi-kim** [comment]
네 확인하였습니다. [cdn.jsdelivr.net](https://cdn.jsdelivr.net/) 서버 SSL 인증서 만료로 생긴 문제로 파악되었습니다.
