### ISSUE TITLE
xeicon 아이콘들이 네모 박스로 보입니다. 

### ISSUE THREAD

**Issue by HEO-AH-YEONG** [xpressengine/XEIcon#54]
공식사이트를 포함해 xeicon을 사용한 사이트들에서 아이콘이 나타나지 않고 있습니다. 
바쁘시겠지만 확인 부탁 드리겠습니다...

**Comment by bi-kim** [comment]
제보 감사드립니다. #53 해당 이슈와 동일한 이슈입니다. 
xeicon을 다운로드하셔서 별도로 구성하셔야 할 것 같습니다.

[XEIcon 2.3.3 다운로드](https://github.com/xpressengine/XEIcon/releases/tag/2.3.3)
