### ISSUE TITLE
가장 최근에 올려져있는 폰트 파일 2.3.3ver이 맞을까요?

### ISSUE THREAD

**Issue by JJUNG-kr** [xpressengine/XEIcon#55]
지금 허브에 올라와있는 'XEIcon-master.zip' 의 fonts 파일이 
https://xpressengine.github.io/XEIcon/library-2.3.3.html
위에 올라와져 있는 2.3.3 최신 폰트인지 여쭤봅니다. 
([XEIcon 2.3.0] 이라고 적혀있습니다.)

문의 읽어주셔서 감사합니다. 좋은 하루 되세요.

**Comment by bi-kim** [comment]
안녕하세요! 해당 버전이 최신 파일입니다.
[XEIcon 2.3.3 다운로드](https://github.com/xpressengine/XEIcon/releases/tag/2.3.3)

관련 이슈 #53 #54
