### ISSUE TITLE
cdn 이슈때문인지 웹사이트 아이콘이 안보입니다

### ISSUE THREAD

**Issue by jheey21** [xpressengine/XEIcon#57]
언제쯤 해결될까요??

**Comment by bi-kim** [comment]
사용 중이신 cdn을 임시로 아래 주소로 연결하셔서 사용하시는 것도 방법이 될 수 있습니다.
`https://fastly.jsdelivr.net/npm/xeicon@2/xeicon.min.css`

관련 이슈 #53, #54 #55, #56, #57
