### ISSUE TITLE
Spinner Test

### ISSUE THREAD

**Issue by junnaa** [xpressengine/XEIcon#7]
### Request
1. SVG->Font(css) 변환시, Opacity가 잘 적용되는지 확인
2. SASS,LESS를 사용한 CSS의 rotate 속도 테스트 
3. Rotate CSS는 IE10

### Works
- 수정시, 되도록 아이콘 수정을 권장
- 테스트 후, Spinner로서 니즈가 낮아보이는 아이콘은 삭제함.
- 추가 요청에 대한 요구사항 지원

**Comment by junnaa** [comment]
@LeeYoonGu @niizguy 
test 요청. 

cdn : 
`<link rel="stylesheet" href="https://s3.amazonaws.com/icomoon.io/49314/spinner/style.css">`

**Comment by niizguy** [comment]
@junnaa 
해당 cdn으로 테스트한 페이지입니다.
http://niizguy.github.io/XEIcon/example_spinner.html

이외에 테스트해야될 아이콘이 있을까요?

**Comment by junnaa** [comment]
done.
