### ISSUE TITLE
웹사이트에 적용시 폰트가 깨집니다.

### ISSUE THREAD

**Issue by seyriz** [xpressengine/XEIcon#9]
!-- XEIcon CSS --
link rel="stylesheet" type="text/css" href="static/fonts/xeicon/xeicon.css"
!--[if lt IE 8]><link rel="stylesheet" href="static/fonts/xeicon/ie7/ie7.css" ![endif]--

div class="xeicon xe-laptop media-left"
이런식으로 적용하였을 때 https://www.dropbox.com/s/lk0v4t3r7r5way3/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202015-01-26%2013.45.42.png?dl=0
이렇게 깨져나옵니다.

**Comment by gunil** [comment]
@seyriz 적용된 페이지 확인 가능할까요?
